sudo: required

language: python

services:
  - postgresql

install:
  - pyenv install
  - pyenv install 3.5.4
  - pyenv install 3.6.3
  - pyenv local 3.6.3 3.5.4
  - pip install flake8
  - pip install detox
  - pip install -e .

script:
  - flake8
  - detox
