language: python

python:
  - "3.5"
  - "3.6"

services:
  - postgresql

install:
  - pip install flake8
  - pip install detox
  - pip install tox-travis
  - pip install -e .

script:
  - flake8
  - detox
